# -*- coding: utf-8 -*-
"""Copy of Probability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tIW3Oq2K9BhCHfxGF9-lLe6Thrf-y9Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style='whitegrid')
np.random.seed(42)

df = sns.load_dataset('tips')
print('Loaded tips dataset:', df.shape)
df.head()

# 1. Numerical vs categorical columns

numerical = df.select_dtypes(include='number').columns.tolist()
categorical = df.select_dtypes(exclude='number').columns.tolist()

print('Numerical  :', numerical)
print('Categorical:', categorical)


# 2. Mean of a numerical column (tip)

print('Mean of tip:', round(df['tip'].mean(), 2))


# 3. Value counts of a categorical column (sex)

print('Sex value counts:')
print(df['sex'].value_counts())





tip = df['tip']

# 1. Mean, median, mode

print('Mean   :', round(tip.mean(), 2))
print('Median :', round(tip.median(), 2))
print('Mode   :', round(tip.mode()[0], 2))


# 2. mean > median ?

print('mean > median ?', tip.mean() > tip.median(), '-> right-skewed')


# 3. Histogram with mean & median lines

plt.figure(figsize=(7, 3.5))

sns.histplot(tip, kde=True)

plt.axvline(tip.mean(), color='red', label='mean')
plt.axvline(tip.median(), color='green', label='median')

plt.legend()
plt.title('tip: mean vs median')
plt.show()

tip = df['tip']

# 1. Range, variance, standard deviation

print('Range :', round(tip.max() - tip.min(), 2))
print('Var   :', round(tip.var(), 2))
print('Std   :', round(tip.std(), 2))


# 2. Q1, Q3, IQR

q1 = tip.quantile(0.25)
q3 = tip.quantile(0.75)
iqr = q3 - q1

print('Q1 (25%):', round(q1, 2))
print('Q3 (75%):', round(q3, 2))
print('IQR     :', round(iqr, 2))


# 3. Most robust measure of spread = IQR
# IQR is more robust to outliers because it uses the middle 50% of the data.

tip = df['tip']

# 1. Five-number summary

five = tip.describe()[['min', '25%', '50%', '75%', 'max']]
print(five)


# 2. Skewness

print('Skewness:', round(tip.skew(), 3))

# Positive skewness means the data leans to the right.


# 3. Box plot of tip

plt.figure(figsize=(7, 2.8))

sns.boxplot(x=tip)

plt.title('Box plot of tip')
plt.show()

# 1. Correlation matrix

corr = df.corr(numeric_only=True)

print(corr.round(2))


# 2. Heatmap of correlation matrix

plt.figure(figsize=(5, 4))

sns.heatmap(
    corr,
    annot=True,
    cmap='Blues',
    vmin=-1,
    vmax=1
)

plt.title('Correlation matrix')
plt.show()


# 3. Full summary

print(df.describe())


# Insights:
# Insight 1: total_bill has the largest standard deviation, so it has more spread.
# Insight 2: total_bill and tip have a strong positive correlation.
# Insight 3: The numerical columns show some right-skewness.