# -*- coding: utf-8 -*-
"""Linear algebra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vPfaAhYglvJzUJVqp--6-1Grt6y6S9h
"""

import numpy as np

T = np.arange(12).reshape(3, 4)
print('T:\n', T)

# 1. ndim and shape
print('ndim:', T.ndim)
print('shape:', T.shape)

# 2. T + T
print('T + T:\n', T + T)

# 3. Transpose (print .T.shape) and reshape to (2, 6)
print('Transpose shape:', T.T.shape)

T_reshape = T.reshape(2, 6)
print('Reshaped T:\n', T_reshape)

import numpy as np

pairs = [
    (np.array([1, 0, 1]), np.array([1, 0, 1])),    # pair 1
    (np.array([1, 2, 3]), np.array([3, 2, 1])),    # pair 2
    (np.array([2, 0, 0]), np.array([0, 5, 0])),    # pair 3
]

def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for i, (u, v) in enumerate(pairs, start=1):
    # 1. L1 and L2 norm of u
    l1 = np.linalg.norm(u, ord=1)
    l2 = np.linalg.norm(u, ord=2)

    # 2. Cosine similarity of u and v
    similarity = cosine(u, v)

    print("Pair", i)
    print("L1 norm:", l1)
    print("L2 norm:", l2)
    print("Cosine similarity:", similarity)
    print()

# 3. Most similar pair = Pair 1

import numpy as np

M = np.array([[4., 2.],
              [2., 3.]])
P = np.array([[0., -1.],
              [1.,  0.]])

# 1. Inverse and trace of M
inv_M = np.linalg.inv(M)

print("Inverse of M:\n", inv_M)
print("Trace of M:", np.trace(M))

# 2. M @ inv(M) == I ?
I = np.eye(2)
print("M @ inv(M) is identity:", np.allclose(M @ inv_M, I))

# 3. Is M symmetric? Is P orthogonal?
print("Is M symmetric?", np.allclose(M, M.T))
print("Is P orthogonal?", np.allclose(P.T @ P, I))

import numpy as np
import matplotlib.pyplot as plt

tri = np.array([[0, 1, 0.5],
                [0, 0, 1.0]])

# Function to close the triangle
def close_loop(points):
    return np.hstack([points, points[:, :1]])

# 1. Scaling matrix (x*2, y*0.5)
S = np.array([[2., 0.],
              [0., 0.5]])

# 2. Rotation matrix (45 degrees)
theta = np.radians(45)

R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

# 3. Apply scaling first, then rotation
scaled_tri = S @ tri
transformed_tri = R @ scaled_tri

# Close the triangles for plotting
original = close_loop(tri)
transformed = close_loop(transformed_tri)

# Plot original vs transformed
plt.plot(original[0], original[1], marker='o', label='Original')
plt.plot(transformed[0], transformed[1], marker='o', label='Transformed')

plt.xlabel('X')
plt.ylabel('Y')
plt.title('Original vs Transformed Triangle')
plt.axis('equal')
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import numpy.linalg as la

C = np.array([[4., 1.],
              [2., 3.]])

# 1. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = la.eig(C)

# 2. Print eigenvalues
print("Eigenvalues:", eigenvalues)

# 3. Verify C v = lambda v for the first eigenvector
v = eigenvectors[:, 0]
lam = eigenvalues[0]

print("Verification:", np.allclose(C @ v, lam * v))

import numpy as np

A2 = np.array([[3., 2.],
               [1., 4.]])
b2 = np.array([7., 9.])

cat = np.array([0.9, 0.8, 0.1])
dog = np.array([0.85, 0.7, 0.2])
car = np.array([0.1, 0.2, 0.95])

# Cosine similarity function
def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

# 1. Solve A2 x = b2
x = np.linalg.solve(A2, b2)
print("Solution x:", x)

# 2. Rank of A2
rank = np.linalg.matrix_rank(A2)
print("Rank of A2:", rank)

# 3. Cosine similarity
cat_dog = cosine(cat, dog)
cat_car = cosine(cat, car)

print("Cosine(cat, dog):", cat_dog)
print("Cosine(cat, car):", cat_car)

# Cat vs Dog is more similar.